dependency:
  name: galaxy
driver:
  name: docker
# We are using yamllint directly in gitlab-ci
# lint: "ansible-lint . --exclude .gitlab-ci.yml"
platforms:
  - name: ubuntu-2004
    image: golovanovsv/ubuntu:20.04-systemd
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
  - name: ubuntu-1804
    image: golovanovsv/ubuntu:18.04-systemd
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
  - name: debian-9
    image: golovanovsv/debian:9-systemd
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
  - name: debian-10
    image: golovanovsv/debian:10-systemd
    command: /lib/systemd/systemd
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
  log: true
  config_options:
    defaults:
      interpreter_python: "python3"
verifier:
  name: testinfra
  directory: ../../tests
  # Uncomment for view print() results
  # options:
  #   s: true
